config/routes.rb
FacebookCaller::Application.routes.draw do

  get "help/index"
  get "home" => "home#index"
  get "home/index" => "home#index"
  post "home/change_token"
  post "home/research_object"
  post "home/refresh_object"
  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @token = session[:token]
    if session[:token].blank?
      @default_object_id="barackobama"
      session[:obj_id] = @default_object_id
    else
      @default_object_id = session[:obj_id]
    end
  end

  def change_token
    if params[:access_token].blank?
      session[:token] = nil
      flash[:notice] = "You have to enter a valid token to get more permissions."
      redirect_to home_index_url
    return
    else
      session[:token] = params[:access_token]
      @token = session[:token]
      @default_object_id = "me"
      session[:obj_id] = @default_object_id
      flash[:notice] = "Token has been well changed!"
      render :index
    return
    end
  end

  def research_object
    if params[:object_id].blank?
      session[:obj_id] = nil
      @error = true
      @data = 'Please enter an object_id.'
      render :partial => "options_data"
    return
    else
      session[:obj_id] = params[:object_id]
      begin
        graph = Koala::Facebook::API.new(session[:token].to_s)
        @data = graph.get_object(session[:obj_id], :metadata => 1)
        @connection_tab = @data["metadata"]["connections"]
        @result_limit = {"All"=>0,"1"=>1,"5"=>5,"10"=>10,"20"=>20,"40"=>40}

      rescue Exception => e
        @error = true
        @data = 'Error '+e.to_s
      end

    end
    render :partial => "options_data"
    return
  end

  def refresh_object
    begin
      graph = Koala::Facebook::API.new(session[:token].to_s)
      @data = graph.get_connections(session[:obj_id], params[:connection_type], :limit => params[:result_limit])
    rescue Exception => e
      @error = true
      @data = 'Error '+e.to_s
    end
    render :partial => "data"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def hash_to_html key,value
    html = ""
    if key.is_a?(Hash)
      html << "<tr><th><i class='icon-arrow-right'></i></th>"
      html << "<td>"
      html << "<table class='table''>"
      key.each do |subkey, subvalue|
        html << hash_to_html(subkey, subvalue)
      end
      html << "</table></td></tr>"
    elsif value.is_a?(Hash)
      html << "<tr><th>#{key} <i class='icon-arrow-right'></i></th>"
      html << "<td>"
      html << "<table class='table''>"
      value.each do |subkey, subvalue|
        html << hash_to_html(subkey, subvalue)
      end
      html << "</table></td></tr>"
    elsif value.is_a?(Array)
      html << "<tr><th>#{key} <i class='icon-arrow-right'></i></th>"
      html << "<td>"
      html << "<table class='table''>"
      value.each do |v|
        html << array_to_html(v)
      end
      html << "</table></td></tr>"
    else
      html << "<tr><th>#{key}:</th><td> #{value}</td></tr>"
    end
    return html
  end

  def array_to_html(value)
    html = ""
    if value.is_a?(Hash)
      html << "<tr><td><table class='table''>"
      value.each do |subkey, subvalue|
        html << hash_to_html(subkey, subvalue)
      end
      html << "</table></td></tr>"
    elsif value.is_a?(Array)
      html << "<tr><td><table class='table''>"
      value.each do |v|
        html << array_to_html(v)
      end
      html << "</table></td></tr>"
    else
      html << "<tr><td> #{value}</td></tr>"
    end
    return html
  end

end

app/views/help/index.html.erb
<%= content_for :active_help, "class=active" %>
<div class="page-header">
	<h1>Facebook Object Visualizer - Help</h1>
</div>

<p>
	<h4>Chargement des données: </h4>
	Le temps de chargement peut varier selon la requête. Il est préférable d'attendre une à cinq secondes après une action.
</p>
<br />
<p>
	<h4>Configuration: </h4>
	L'application utilise le plugin Koala GraphAPI - <a href="https://github.com/arsduo/koala/wiki/Graph-API">Github</a>
</p>
<br />
<p>
	<h4>Récupérer votre token: </h4>
	<a href="http://tltest.heroku.com/">http://tltest.heroku.com/</a>

	Le token n'est pas indispensable. Sans lui, il est possible de récupérer les informations publiques d'un objet facebook.
	Pour cela, il faut renseigner le champ 'Object id' avec l'identifiant de l'objet recherché. (exemple: barackobama)
</p>
<br />

<p>
	<h4>Requête qui échoue ?</h4>
	<ul>
		<li>
			Vérifier le token.
		</li>
		<li>
			Vérifier le 'object id'.
		</li>
		<li>
			Les deux sont bon? Réessayez. Si ça ne marche toujours pas, contactez moi : sylvestre[dot]antoine[at]gmail[dot]com
		</li>
	</ul>
</p>

app/views/home/_data.html.erb
<h3> Data :</h3>
<% if @data %>
	<% if @error %>
	<div id="error_explanation">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<%= @data %>
	</div>
	<% else %>
		<table class="table">
		<% @data.each do |key, value| %>
		<%= raw(hash_to_html(key, value)) %>
		<% end %>
		</table>
	<% end %>
<% end %>

app/views/home/_options_data.html.erb
<h3> Select Options </h3>

<% if !@connection_tab.blank? %>
<p>
	<%= label_tag(:connection_type, "Choose connection type") %>
	<%= select_tag(:connection_type, options_from_collection_for_select(@connection_tab, :first, :first), :include_blank => true) %>
</p>
<p>
	<%= label_tag(:result_limit, "Number of results") %>
	<%= select_tag(:result_limit, options_from_collection_for_select(@result_limit, :last, :first)) %>
</p>
<%= link_to "Refresh" , '', :class => 'btn btn-secondary', :id => 'fb_refresh' %>
<% end %>

app/views/home/index.html.erb
<%= content_for :active_home, "class=active" %>
<div class="page-header">
	<h1>Facebook API - Search data</h1>
</div>

<% if notice %>
<div id="notice" class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">
		×
	</button>
	<%= notice %>
</div>
<% end %>

<div class="row">
	<div class="center">
		<div class="span12">
			<div class="well">
				<%= form_tag :controller => 'home', :action => 'change_token' do %>
				<%= label_tag(:access_token, "Enter an FB Access Token") %>
				<%= text_field_tag(:access_token) %>
				<%= submit_tag "Change Token", :class => 'btn btn-primary' %>
				<% end %>
				<% unless @token.blank? %>
				<p>
					Your current access token : <%= @token %>
				</p>
				<% end %>
			</div>
		</div>
		<div class="span6">
			<div class="well fixed_height" style="min-height: 240px;"²>
				<h3> Select Object ID : </h3>
				<%= label_tag(:object_id, "Enter an FB Object ID") %>
				<%= text_field_tag(:object_id, @default_object_id) %>
				<%= link_to "Search object" , '', :class => 'btn btn-primary', :id => 'fb_research' %>
				<hr />
				Examples: me or barackobama
			</div>
		</div>
		<div class="span6">
			<div class="well fixed" style="min-height: 240px;">
				<div id="option_data">
					<%= render :partial => 'options_data' %>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="span12">
		<div class="well">
			<div id="data" >
				<%= render :partial => 'data' %>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$("#fb_research").live('click', fb_research);
	$("#fb_refresh").live('click', fb_refresh);

	function fb_research() {
		var object_id = $('#object_id').val();
		var access_token = $('#access_token').val();

		jQuery.post("<%= home_research_object_path %>", {
			object_id : object_id,
			access_token : access_token
		}, function(data) {
			$("#option_data").html(data);
		});
		fb_refresh();
		return false;
	}

	function fb_refresh() {
		var connection_type = $('#connection_type').val();
		var result_limit = $('#result_limit').val();
		var object_id = $('#object_id').val();

		jQuery.post("<%= home_refresh_object_path %>", {
			connection_type : connection_type,
			result_limit : result_limit,
			object_id : object_id
		}, function(data) {
			$("#data").html(data);
		});
		return false;
	}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Facebook Object Visualizer</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= javascript_include_tag "bootstrap" %>
	</head>
	<body>
		<div class="navbar navbar-fixed-top">

			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="/">Simple Facebook Object Visualizer App</a>
					<ul class="nav">
						<li <%= yield(:active_home) %>>
							<%= link_to 'Home', home_index_path %>
						</li>
						<li <%= yield(:active_help) %>>
							<%= link_to 'Help', help_index_path %>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="container" style="margin-top: 60px;">
			<%= yield %>
		</div>

		<footer>
			<div>
				<p>
					Facebook Object Visualizer @ 2012
				</p>
			</div>
		</footer>
	</body>
</html>